// Generates res/fonts.scss with self-hosted Clear Sans (Apache-2.0) latin
// subsets embedded as base64 data URIs. Run: npm run build:fonts
import {mkdirSync, readFileSync, writeFileSync} from "node:fs"
import {dirname, resolve} from "node:path"
import {fileURLToPath} from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, "..")
const filesDir = resolve(root, "node_modules/@fontsource/clear-sans/files")
const outFile = resolve(root, "res/fonts.scss")

const weights = [400, 500, 700]

let css = "// Generated by tools/gen-fonts.mjs — do not edit by hand.\n"
for (const weight of weights) {
  const woff2 = resolve(filesDir, `clear-sans-latin-${weight}-normal.woff2`)
  const b64 = readFileSync(woff2).toString("base64")
  css +=
    "@font-face {\n" +
    '  font-family: "Clear Sans";\n' +
    "  font-style: normal;\n" +
    `  font-weight: ${weight};\n` +
    "  font-display: swap;\n" +
    `  src: url(data:font/woff2;base64,${b64}) format("woff2");\n` +
    "}\n"
}

mkdirSync(dirname(outFile), {recursive: true})
writeFileSync(outFile, css)
console.log(`wrote ${outFile} (${css.length} bytes)`)
