/* @generated by: make gen-init-blob-bindings — do not edit manually. */
#ifndef LIBKRUN_INIT_H
#define LIBKRUN_INIT_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

typedef void* KrunInitConfigError;
typedef void* KrunInitApplyError;
typedef void* KrunInitConfig;
typedef void* KrunInitBuilder;
typedef void* KrunInitError; /* KrunInitConfigError | KrunInitApplyError | KrunInitVtableError */
typedef void* KrunInitPushStr; /* KrunInitVtablePushStr */
typedef void* KrunFsOverlay;
typedef void* KrunPayload;

#ifndef KRUN_PRIMITIVES_DEFINED
#define KRUN_PRIMITIVES_DEFINED

typedef void* KrunObject; /* KrunInitConfigError | KrunInitApplyError | KrunInitConfig | KrunInitBuilder */

typedef uint64_t KrunResult;
#define KRUN_RESULT_SUCCESS 0

/* Caller must ensure data is valid UTF-8 */
typedef struct {
    const char* data;
    size_t len;
} KrunStr;

#define KRUN_STR(s) ((KrunStr){ .data = (s), .len = (s) ? strlen(s) : 0 })
/**
 * Stack-allocated temporary handle for passing vtable-based objects.
 * Only valid for the duration of the call — the callee borrows, not owns.
 */
typedef struct {
    uint32_t type_tag;
    uint32_t metadata;
    const void *vtable_ptr;
    const void *user_data;
    uint16_t vtable_size;
} KrunVtableHandle;

#define KRUN_VTABLE_HANDLE(tag, vtable, self_data) \
    ((KrunVtableHandle){ .type_tag = (tag), .metadata = 0, \
      .vtable_ptr = &(vtable), .user_data = (self_data), \
      .vtable_size = sizeof(vtable) })

/**
 * Opaque 16-byte handle entry in an object array.
 * Do not access fields directly — pass &entry to typed methods.
 * Do NOT pass individual entries to destroy.
 */
typedef struct {
    uint32_t _tag;
    uint32_t _meta;
    const void* _ptr;
} KrunObjectArrayEntry;

/**
 * Contiguous array of borrowed handles.
 * Returned by methods that produce slices of handles.
 * Individual elements must NOT be passed to destroy —
 * call free_object_array() to free the entire array.
 */
typedef struct {
    const KrunObjectArrayEntry* items;
    size_t len;
} KrunObjectArray;

#define KRUN_OBJECT_ARRAY_GET(arr, i) \
    (assert((size_t)(i) < (arr).len), (KrunObject)(void*)&(arr).items[(i)])

#endif /* KRUN_PRIMITIVES_DEFINED */

/* Free an owned string returned by the library */
void krun_init_str_free(KrunStr s);
typedef void (*krun_init_str_free_fn)(KrunStr s);

/* Free an object array returned by the library */
void krun_init_free_object_array(KrunObjectArray a);
typedef void (*krun_init_free_object_array_fn)(KrunObjectArray a);


/* ConfigError ------------------------------------------------------- */

#define KRUN_INIT_ERROR_CONFIG_INVALID_JSON ((uint64_t)33554435 << 32 | 1)

/* ApplyError -------------------------------------------------------- */

#define KRUN_INIT_ERROR_APPLY_SYMBOL_NOT_FOUND ((uint64_t)33554438 << 32 | 1)
#define KRUN_INIT_ERROR_APPLY_OVERLAY_ERROR ((uint64_t)33554438 << 32 | 2)

/* Config ------------------------------------------------------------ */

/** Start building a new init configuration. */
KrunInitBuilder krun_init_config_builder();
typedef KrunInitBuilder (*krun_init_config_builder_fn)();
/**
 * Apply this init configuration to a VM's filesystem overlay and payload.
 *
 * Adds the init binary and associated configuration file(s) as overlay
 * files, and appends the init kernel command line argument to the payload.
 *
 * The caller must keep this `Config` (or `KrunInitConfig`) alive for the
 * entire lifetime of the VM; `apply` borrows data pointers that remain
 * referenced until the VM exits.
 *
 * Symbols are loaded from the global namespace (`RTLD_DEFAULT`).
 */
KrunResult krun_init_config_apply(KrunInitConfig handle, KrunFsOverlay overlay, KrunPayload payload, KrunInitError* err_out);
typedef KrunResult (*krun_init_config_apply_fn)(KrunInitConfig handle, KrunFsOverlay overlay, KrunPayload payload, KrunInitError* err_out);
/**
 * Like [`apply`](Self::apply), but loads symbols from a specific library
 * handle (e.g. from `dlopen`). Pass null for `RTLD_DEFAULT`.
 *
 * - If `lib_handle` is non-null it must be a valid handle returned by
 *   `dlopen` (or equivalent) that remains open for the duration of
 *   this call.
 * - The caller must keep this `Config` (or `KrunInitConfig`) alive for the
 *   entire lifetime of the VM.
 */
KrunResult krun_init_config_apply_in(KrunInitConfig handle, void* lib_handle, KrunFsOverlay overlay, KrunPayload payload, KrunInitError* err_out);
typedef KrunResult (*krun_init_config_apply_in_fn)(KrunInitConfig handle, void* lib_handle, KrunFsOverlay overlay, KrunPayload payload, KrunInitError* err_out);
void krun_init_config_destroy(KrunInitConfig handle);
typedef void (*krun_init_config_destroy_fn)(KrunInitConfig handle);

/* Builder ----------------------------------------------------------- */

/**
 * Parse an OCI runtime-spec config.json string into a builder.
 *
 * Unknown fields are silently ignored. The caller can further
 * modify the builder (e.g. add rlimits, mounts) before calling
 * [`build()`](Self::build).
 */
KrunInitBuilder krun_init_builder_from_oci_json(KrunStr json, KrunInitError* err_out);
typedef KrunInitBuilder (*krun_init_builder_from_oci_json_fn)(KrunStr json, KrunInitError* err_out);
/** Append a single argument to argv. */
void krun_init_builder_arg(KrunInitBuilder* handle, KrunStr arg);
typedef void (*krun_init_builder_arg_fn)(KrunInitBuilder* handle, KrunStr arg);
/** Append multiple arguments to argv. */
void krun_init_builder_args(KrunInitBuilder* handle, const KrunStr* argv, size_t argv_len);
typedef void (*krun_init_builder_args_fn)(KrunInitBuilder* handle, const KrunStr* argv, size_t argv_len);
/** Append a single environment variable (`"KEY=value"`). */
void krun_init_builder_env_var(KrunInitBuilder* handle, KrunStr var);
typedef void (*krun_init_builder_env_var_fn)(KrunInitBuilder* handle, KrunStr var);
/** Append multiple environment variables. */
void krun_init_builder_env(KrunInitBuilder* handle, const KrunStr* vars, size_t vars_len);
typedef void (*krun_init_builder_env_fn)(KrunInitBuilder* handle, const KrunStr* vars, size_t vars_len);
/** Set the guest working directory. */
void krun_init_builder_workdir(KrunInitBuilder* handle, KrunStr dir);
typedef void (*krun_init_builder_workdir_fn)(KrunInitBuilder* handle, KrunStr dir);
/** Add a mount specification. */
void krun_init_builder_mount(KrunInitBuilder* handle, KrunStr destination, KrunStr fs_type, KrunStr source);
typedef void (*krun_init_builder_mount_fn)(KrunInitBuilder* handle, KrunStr destination, KrunStr fs_type, KrunStr source);
/** Append a single resource limit (`"id=cur:max"`, e.g. `"7=0:0"`). */
void krun_init_builder_rlimit(KrunInitBuilder* handle, KrunStr limit);
typedef void (*krun_init_builder_rlimit_fn)(KrunInitBuilder* handle, KrunStr limit);
/** Append multiple resource limits. */
void krun_init_builder_rlimits(KrunInitBuilder* handle, const KrunStr* limits, size_t limits_len);
typedef void (*krun_init_builder_rlimits_fn)(KrunInitBuilder* handle, const KrunStr* limits, size_t limits_len);
/** Enable DHCP client in the guest. */
void krun_init_builder_dhcp(KrunInitBuilder* handle, bool enable);
typedef void (*krun_init_builder_dhcp_fn)(KrunInitBuilder* handle, bool enable);
/** Set the root disk to remount on boot. */
void krun_init_builder_set_root_disk_remount(KrunInitBuilder* handle, KrunStr device, KrunStr fstype, KrunStr options);
typedef void (*krun_init_builder_set_root_disk_remount_fn)(KrunInitBuilder* handle, KrunStr device, KrunStr fstype, KrunStr options);
/**
 * Consume the builder, serialize the config, and return the
 * finished [`Config`].
 */
KrunInitConfig krun_init_builder_build(KrunInitBuilder* handle);
typedef KrunInitConfig (*krun_init_builder_build_fn)(KrunInitBuilder* handle);
void krun_init_builder_destroy(KrunInitBuilder handle);
typedef void (*krun_init_builder_destroy_fn)(KrunInitBuilder handle);

/* KrunInitPushStrVtable --------------------------------------------- */

#define KRUN_INIT_PUSH_STR_TYPE_TAG 33554433

typedef struct {
    void (*drop)(void* self_data);
    bool (*push)(void* self_data, KrunStr s);
} KrunInitPushStrVtable;

/* PushStr (dispatch) ------------------------------------------------ */

bool krun_init_push_str_push(KrunInitPushStr handle, KrunStr s);
typedef bool (*krun_init_push_str_push_fn)(KrunInitPushStr handle, KrunStr s);
void krun_init_push_str_destroy(KrunInitPushStr handle);
typedef void (*krun_init_push_str_destroy_fn)(KrunInitPushStr handle);

/* KrunInitErrorVtable ----------------------------------------------- */

#define KRUN_INIT_ERROR_TYPE_TAG 33554434

typedef struct {
    void (*drop)(void* self_data);
    uint32_t (*code)(void* self_data);
    void (*message)(void* self_data, KrunInitPushStr writer);
    uint64_t (*result)(void* self_data);
} KrunInitErrorVtable;

/* Error (dispatch) -------------------------------------------------- */

uint32_t krun_init_error_code(KrunInitError handle);
typedef uint32_t (*krun_init_error_code_fn)(KrunInitError handle);
void krun_init_error_message(KrunInitError handle, KrunInitPushStr writer);
typedef void (*krun_init_error_message_fn)(KrunInitError handle, KrunInitPushStr writer);
uint64_t krun_init_error_result(KrunInitError handle);
typedef uint64_t (*krun_init_error_result_fn)(KrunInitError handle);
void krun_init_error_destroy(KrunInitError handle);
typedef void (*krun_init_error_destroy_fn)(KrunInitError handle);
uint32_t krun_init_config_error_code(KrunInitConfigError handle);
typedef uint32_t (*krun_init_config_error_code_fn)(KrunInitConfigError handle);
void krun_init_config_error_message(KrunInitConfigError handle, KrunInitPushStr writer);
typedef void (*krun_init_config_error_message_fn)(KrunInitConfigError handle, KrunInitPushStr writer);
uint32_t krun_init_apply_error_code(KrunInitApplyError handle);
typedef uint32_t (*krun_init_apply_error_code_fn)(KrunInitApplyError handle);
void krun_init_apply_error_message(KrunInitApplyError handle, KrunInitPushStr writer);
typedef void (*krun_init_apply_error_message_fn)(KrunInitApplyError handle, KrunInitPushStr writer);
KrunStr krun_init_result_name(KrunResult r);
typedef KrunStr (*krun_init_result_name_fn)(KrunResult r);
const char* krun_init_result_name_cstr(KrunResult r);
typedef const char* (*krun_init_result_name_cstr_fn)(KrunResult r);

#endif /* LIBKRUN_INIT_H */
